apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterfs-block-<nu>
  annotations:
     volume.beta.kubernetes.io/storage-class: glusterfs-storage-block
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
